FROM ruby:2.5.1

RUN apt-get update -qq && \
  apt-get install -y build-essential libpq-dev nodejs postgresql-client yarn

WORKDIR /app
COPY Gemfile Gemfile.lock /app/
RUN gem install bundler
RUN bundle install
COPY . /app

EXPOSE 3000
